version: '3'

services:
    app:
        build: .
        container_name: start-with-django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/home/django/app
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: postgres
        container_name: start-django-db
        tty: true
        environment:
            - POSTGRES_DB=start_django
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        volumes:
            - start-django-pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: start-django-pgadmin
        tty: true
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@user.com
            - PGADMIN_DEFAULT_PASSWORD=123456
        ports:
          - "9000:80"

volumes:
    start-django-pgdata:
        external: true